services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD:-password}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - rubber-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.4
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD:-password}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-adminpwd}
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_HTTP_ENABLED: "true"
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME: https://51.222.109.63:40081
      KC_HOSTNAME_STRICT: "true"
      KC_HOSTNAME_STRICT_HTTPS: "true"
    command: start --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
      - ./keycloak/my-theme:/opt/keycloak/themes/my-theme 
    ports:
      - "8181:8080"
    networks:
      - rubber-net
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/realms/rubberduck"]
      interval: 10s
      timeout: 5s
      retries: 12

  pulsar:
    image: apachepulsar/pulsar:2.10.2
    container_name: pulsar
    command: >
      bash -c "bin/pulsar standalone --no-functions-worker"
    volumes:
      - pulsar-data:/pulsar/data
    ports:
      - "6650:6650"
      - "3080:8080"
    networks:
      - rubber-net
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8080/admin/v2/brokers/localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 12

networks:
  rubber-net:
    driver: bridge

volumes:
  pulsar-data:
  postgres-data:


